### ISSUE TITLE
Root page is return 404 page, i fresh installation

### ISSUE THREAD

**Issue by rdp77** [Hasnayeen/invobook#1484]
![image](https://github.com/Hasnayeen/invobook/assets/25810647/0efb7724-c124-4c7c-8764-9c098b33ce8c)

I have done the installation procedure starting from composer to database setup, but the root page returns 404 page, I run it on local

**Comment by coachben** [comment]
You may have to run these 2 commands:

- php artisan route:list    - This will show you all the routes used in application. (It is a poor design not to have them in the web.php router file for ex.)

- nom run dev  - This will launch Site
- Access your application routes - for ex. invobook.test/app and start hacking your way into the application
