### ISSUE TITLE
composer update issue

### ISSUE THREAD

**Issue by vitalijalbu** [Hasnayeen/invobook#1487]
i just ran composer update

<img width="948" alt="Screenshot 2023-12-05 alle 15 59 52" src="https://github.com/Hasnayeen/invobook/assets/40239902/b1241e47-3a5d-4903-b87a-e1d14c693122">

**Comment by Sriramhetsolutionspa** [comment]
i am too getting the same error 
try to change the title to something like " Error: CumulativeEarningsPerDay contains 2 abstract methods and must therefore be declared abstract" and tag the author @Hasnayeen

**Comment by Hasnayeen** [comment]
fixed by fdac597
